In [1]:
# Two data structures used: Python list, Numpy ndarray

##### Python Lists #####
# Note: [] is list, () is tuple
# Note: Python uses 0 indexing
L = [0, 2, 4, 6, 8]
L[0] = L[2]*L[4]
print(L)

[32, 2, 4, 6, 8]


In [2]:
# lists can be appended!
L.append(100)
print(L)

[32, 2, 4, 6, 8, 100]


In [3]:
# and extended with another list
L.extend([200, 300])
print(L)

[32, 2, 4, 6, 8, 100, 200, 300]


In [4]:
# and you can also pop items by the index
L.pop(2)
print(L)

[32, 2, 6, 8, 100, 200, 300]


In [5]:
# but normal operations work differently
# + works to add lists, not add to every element in the list
print(L + [2, 3])

[32, 2, 6, 8, 100, 200, 300, 2, 3]


In [6]:
# * works to duplicate lists by that amount of time
print(L*3)

[32, 2, 6, 8, 100, 200, 300, 32, 2, 6, 8, 100, 200, 300, 32, 2, 6, 8, 100, 200, 300]


In [7]:
# finally, lists are not type-specific -- you can store other things there!
print(L + ["halleloo", 'a'])

[32, 2, 6, 8, 100, 200, 300, 'halleloo', 'a']


In [8]:
##### Python ndarray #####
# Numpy - why Python is good for science
# ndarrays are C arrays

# e.g. arange is the Numpy version of range
import numpy as np
a = np.arange(0, 100, 15)
print(a)

[ 0 15 30 45 60 75 90]


In [9]:
# you can read and write into a numpy array
print(a[2])

30


In [10]:
a[0] = 999
print(a)

[999  15  30  45  60  75  90]


In [11]:
# you can get a 'sub-array' from a numpy array by passing a list
b = [0, 2, 4]
print(a[b])

[999  30  60]


In [12]:
# and write a single value to multiple locations as well
a[b] = -100
print(a)

[-100   15 -100   45 -100   75   90]


In [13]:
# or an array of values as long as they're the same size
a[[1, 3, 5]] = [111, 222, 333]
print(a)

[-100  111 -100  222 -100  333   90]


In [14]:
# and filter and map using a predicate called mask
mask = a < 0
a[mask] = 0
print(a)

[  0 111   0 222   0 333  90]


In [15]:
##### Vectorization #####
# ndarrays can be treated as vectors and you can perform vector operations
print(a*2)

[  0 222   0 444   0 666 180]


In [16]:
print(a*[1, 2, 3, 4, 5, 6, 7])

[   0  222    0  888    0 1998  630]


In [17]:
print(a + 2)

[  2 113   2 224   2 335  92]


In [18]:
print(a + [7, 6, 5, 4, 3, 2, 1])

[  7 117   5 226   3 335  91]


In [19]:
##### Methods vs. Functions #####
# e.g. summing can be done by using a numpy function (sum)
arr = np.array([1, 2, 3, 4])
print(np.sum(arr))

10


In [20]:
# or calling a method in the numpy object
# depends on what you prefer
print(arr.sum())

10


In [21]:
##### Dictionaries #####
# like a list but items are addressed by name -- composed of key and value pairs
d = dict()
d['arr'] = a
d['list'] = L
print(d)

{'arr': array([  0, 111,   0, 222,   0, 333,  90]), 'list': [32, 2, 6, 8, 100, 200, 300]}


In [22]:
# you can "index" it as well
print(d['arr'])

[  0 111   0 222   0 333  90]


In [23]:
# you can also get the list of keys
d.keys()

dict_keys(['arr', 'list'])

In [24]:
# and values
d.values()

dict_values([array([  0, 111,   0, 222,   0, 333,  90]), [32, 2, 6, 8, 100, 200, 300]])

In [25]:
# add items by specifying a distinct key name
d['test'] = 1.0
print(d)

{'arr': array([  0, 111,   0, 222,   0, 333,  90]), 'list': [32, 2, 6, 8, 100, 200, 300], 'test': 1.0}


In [26]:
# you can delete values too
del d['test']
print(d.keys())

dict_keys(['arr', 'list'])


In [27]:
# or pop it
arr = d.pop('arr')
print(d)

{'list': [32, 2, 6, 8, 100, 200, 300]}


In [28]:
##### Dictionary Inheritance and Subclasses #####
# using the [] to index actually calls __getitem__ and __setitem__ methods - intrinsic methods

# create a class to add functionalities to __getitem__ and __setitem__
class NewDict(dict): 
    
    def __setitem__(self, key, value):
        # Define customization
        print("The key being written is:", key)
        print("The value being written is:", value)
        # And call the actual setitem
        super().__setitem__(key, value)
        
    def __getitem__(self, key):
        print("The key being retrieved is:", key)
        return super().__getitem__(key)


In [29]:
dnew = NewDict()
# calls the new __setitem__
dnew['test'] = 1.0

The key being written is: test
The value being written is: 1.0


In [30]:
# calls the new __getitem__
dnew['test']

The key being retrieved is: test


1.0

In [31]:
# OpenPNM overloads __setitem__ and __getitem__ to perform several checks
import openpnm as op
pn = op.network.Demo()
try:
    pn['foo.bar'] = 1.0
except Exception as e:
    print(e)

All dict names must start with pore, throat, or param


In [32]:
# this can be niniced using the NewDict class
class NewDict(dict): 
    
    def __setitem__(self, key, value):
        if not (key.startswith('pore') or key.startswith('throat')):
            raise Exception('Key must start with either pore, or throat')
        super().__setitem__(key, value)

dnew = NewDict()
try:
    dnew['foo.test'] = 1.0
except Exception as e:
    print(e)
dnew['pore.test'] = 1.0
print(dnew.keys())

Key must start with either pore, or throat
dict_keys(['pore.test'])


In [33]:
# subclassing also allows to add new functions
class NewDict(dict): 
    
    def __setitem__(self, key, value):
        if not (key.startswith('pore') or key.startswith('throat')):
            raise Exception('Key must start with either pore, or throat')
        super().__setitem__(key, value)
    
    def poreprops(self):
        print('The following pore properties were found:')
        for item in self.keys():
            if item.startswith('pore'):
                print('-> ' + item)


In [34]:
dnew = NewDict()
dnew['pore.test'] = 1.0
dnew['pore.bar'] = 100
dnew['throat.blah'] = 2.0
dnew.poreprops()

The following pore properties were found:
-> pore.test
-> pore.bar


In [35]:
# and you can add attributes to a subclassed dict
dnew.name = 'bob'
print(dnew.name)

bob


In [36]:
# and even other dictionaries (that you initialize using {})
dnew.settings = {}
dnew.settings['name'] = 'bob'
print(dnew.settings)

{'name': 'bob'}
